CREATE TABLE payment_methods (
    -- for mysql use this code
    -- id INT PRIMARY KEY AUTO_INCREMENT,
    -- for postgresql use this code
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

CREATE TABLE tables (
    -- for mysql use this code
    -- id INT PRIMARY KEY AUTO_INCREMENT,
    -- for postgresql use this code
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_seats INT,
    category VARCHAR(200)
);


