-- 1 создать базу данных shop
CREATE DATABASE shop;
-- 2 добавить таблицу products
CREATE TABLE products(
    product_name VARCHAR(500) NOT NULL ,
    price INT,
    description TEXT NOT NULL,
    amount_in_stock INT,
    image_url VARCHAR(600) NOT NULL
);
-- 3 настроить столбцы, указать типы данных

-- 4 вставить тестовые данные
INSERT INTO products(product_name, price, description, amount_in_stock, image_url)
VALUES ('Table',25,'Table is wood',5,'src/public/table.jpg' );
-- 5 обновить таблицу и добавить ограничения
ALTER TABLE products
ADD CONSTRAINT products_prise CHECK ( price > 0 ),
ADD CONSTRAINT products_amount_in_stock  CHECK ( amount_in_stock > 0 AND amount_in_stock  < 999);
-- 6 обновить таблицу и добавить первичный ключ
ALTER TABLE products
ADD COLUMN id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE products
ALTER COLUMN price SET DATA TYPE NUMERIC(10,2)

-- DROP TABLE products