CREATE TABLE employees(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    birthdate DATE NOT NULL ,

    email VARCHAR(300) REFERENCES intranet_accounts(email) ON DELETE CASCADE UNIQUE -- 1:1
);


CREATE TABLE projects(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL ,
    deadline DATE NOT NULL
);


CREATE TABLE intranet_accounts(
    email VARCHAR(300) PRIMARY KEY,
    password VARCHAR(500) NOT NULL
);


