CREATE TABLE employees(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    birthdate DATE NOT NULL ,

    email VARCHAR(300) REFERENCES intranet_accounts(email) ON DELETE CASCADE UNIQUE, -- 1:1
    id_teams INT DEFAULT 1 REFERENCES teams(id) ON DELETE SET NULL -- 1:n

);

CREATE TABLE teams(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR(250) NOT NULL,

    id_building INT REFERENCES buildings(id) ON DELETE SET NULL
);

CREATE TABLE buildings(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(500)
);


CREATE TABLE projects(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL ,
    deadline DATE NOT NULL
);

CREATE TABLE employees_projects(
    id_employee INT REFERENCES  employees(id) ON DELETE CASCADE,
    id_project INT REFERENCES projects(id) ON DELETE CASCADE,
    PRIMARY KEY (id_employee,id_project)
);

CREATE TABLE intranet_accounts(
    email VARCHAR(300) PRIMARY KEY,
    password VARCHAR(500) NOT NULL
);


