CREATE TABLE customers(

    -- for postgresql use this code
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(200),
    last_name VARCHAR(200),
    email VARCHAR(200)
);

CREATE TABLE orders(

    -- for postgresql use this code
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_billed NUMERIC(5, 2),
    customer_id INT REFERENCES customers
);